<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HrDesignationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('hr_designation')->truncate();
        $rows = [
            [
                'client_id' => 188,
                'code' => '002',
                'name_np' => 'शिक्षा अधिकृत',
                'name_en' => 'Education Officer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '015000',
                'name_np' => 'चेक',
                'name_en' => 'Check ',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '004',
                'name_np' => ' स॰पाचौं',
                'name_en' => 'The fifth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '005',
                'name_np' => ' स॰चौथो',
                'name_en' => 'ourth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '006',
                'name_np' => 'श्रोतब्य',
                'name_en' => 'source',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '007',
                'name_np' => ' कायार्लय सहायक',
                'name_en' => 'Office Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '008',
                'name_np' => ' कायार्लय सहायक २',
                'name_en' => 'Office Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '010',
                'name_np' => 'सवारी चालक प्रथम',
                'name_en' => 'Social Administrator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '011',
                'name_np' => ' सामाजीक परिचालक',
                'name_en' => 'social operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '016',
                'name_np' => 'सव-ईन्जिनियर',
                'name_en' => 'Sub-Engineer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '017',
                'name_np' => ' ईन्जिनियर',
                'name_en' => 'Engineer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '018',
                'name_np' => 'कम्युटर सहायक',
                'name_en' => 'Computer Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '019',
                'name_np' => 'सामाजिक परिचालक',
                'name_en' => 'social operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '020',
                'name_np' => ' कार्यालय सहयोगी',
                'name_en' => 'office assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '021',
                'name_np' => 'हेल्थ असिस्टेन',
                'name_en' => 'Health Assist',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '022',
                'name_np' => 'सि॰अ॰न॰मि॰',
                'name_en' => 'C.N.M.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '023',
                'name_np' => ',अ॰हे॰ब॰ ',
                'name_en' => 'A. B.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '024',
                'name_np' => 'अ॰न॰मि॰ चौथो तह ',
                'name_en' => ' A. N. M. Fourth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '025',
                'name_np' => 'वैध अधिकृत',
                'name_en' => 'authorized officer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '026',
                'name_np' => ' अ॰न॰मि॰',
                'name_en' => '  A. N. M.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '027',
                'name_np' => ' कविराज निरीक्षक',
                'name_en' => ' Kaviraj Inspector',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '028',
                'name_np' => 'वैध ',
                'name_en' => 'valid',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '029',
                'name_np' => 'कार्यालय सहायक ',
                'name_en' => ' Office Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '033',
                'name_np' => 'पशु विकास अधिकृत',
                'name_en' => 'Animal Development Officer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '034',
                'name_np' => 'भेटेरीनरी',
                'name_en' => 'Veterinary',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '035',
                'name_np' => 'पशु सेवा प्राविधिक ',
                'name_en' => 'Animal Services Technician',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '15001',
                'name_np' => 'सि॰वि॰आर॰एफ॰',
                'name_en' => 'CVRF',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '36',
                'name_np' => ' कम्प्युटर अपरेटर',
                'name_en' => 'Computer Operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '38',
                'name_np' => 'लेखापाल ',
                'name_en' => 'Accountant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '39',
                'name_np' => 'रोजगार संयोजक',
                'name_en' => 'Employment Coordinator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '40',
                'name_np' => 'नायब सुब्बा ',
                'name_en' => ' Deputy Subba',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '41',
                'name_np' => 'खरिदार ',
                'name_en' => 'buyer',
                'status' => true,
            ],   [
                'client_id' => 188,
                'code' => '42',
                'name_np' => 'प्राविधीक सहायक ',
                'name_en' => ' Technical Assistant',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '43',
                'name_np' => 'एम॰आई॰एस॰ अपरेटर ',
                'name_en' => 'MIS Operator',
                'status' => true,
            ],   [
                'client_id' => 188,
                'code' => '44',
                'name_np' => 'नायब पशुु स्वास्थ्य प्राविधिक',
                'name_en' => 'Deputy Animal Health Technician',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '45',
                'name_np' => 'ल्याब टेक्निसियन ',
                'name_en' => 'Lab Technician',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '46',
                'name_np' => 'सि॰अ॰हे॰ब॰',
                'name_en' => ' C. A. H. B.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '47',
                'name_np' => 'सहायक चौथो ',
                'name_en' => 'Assistant Fourth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '48',
                'name_np' => 'स॰म॰वि॰नि॰ ',
                'name_en' => 'S.M.V.N.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '49',
                'name_np' => 'फिल्ड सहायक ',
                'name_en' => ' Field Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '50',
                'name_np' => 'एम॰आई॰एस॰ अपरेटर ',
                'name_en' => 'MIS Operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '51',
                'name_np' => ' शिक्षक',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '52',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'Head Master',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '53',
                'name_np' => 'पुर्व प्राथमिक शिक्षक ',
                'name_en' => ' Former primary teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '55',
                'name_np' => 'विद्यालय सहयोगी ',
                'name_en' => 'School helper',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '56',
                'name_np' => 'शिक्षक ',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '57',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'Headmaster',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '104',
                'name_np' => 'प्र॰अ॰ ',
                'name_en' => ' Q. A.',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '101',
                'name_np' => 'शिक्षक * ',
                'name_en' => 'Teacher*',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '59',
                'name_np' => ' प्रधानाध्यापक ',
                'name_en' => 'Headmaster',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '58',
                'name_np' => 'शिक्षक ',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '013',
                'name_np' => 'सि॰अ॰न॰मि॰छैटौँ ',
                'name_en' => 'C. A. N. M. Sixth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '101',
                'name_np' => 'प्रारम्भिक बाल विकाश शिक्षक ',
                'name_en' => 'Early Childhood Development Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '102',
                'name_np' => 'कार्यालय सहयोगी  ',
                'name_en' => ' office assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '103',
                'name_np' => 'का॰स॰ ',
                'name_en' => 'kas',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '37',
                'name_np' => 'सुचना प्रविधी अधिकृत ',
                'name_en' => 'I.T. Officer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '60',
                'name_np' => 'सहयोगी कार्यकर्ता ',
                'name_en' => 'support worker',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '61',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'HeadMaster',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '62',
                'name_np' => ' शिक्षक',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '63',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'HeadMaster',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '64',
                'name_np' => 'शिक्षक ',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '65',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'HeadMaster',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '66',
                'name_np' => 'शिक्षक ',
                'name_en' => 'Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '67',
                'name_np' => 'कार्यालय सहायक ',
                'name_en' => 'Office Assistant',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '68',
                'name_np' => 'पुस्तकालय कर्मचारी',
                'name_en' => 'Library staff',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '69',
                'name_np' => ' विद्यालय सरसफाई ',
                'name_en' => 'School cleanliness',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '80',
                'name_np' => 'सहायक कम्प्युटर अपरेटर ',
                'name_en' => 'Assistant Computer Operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '78',
                'name_np' => ' सब-ईन्जिनियर',
                'name_en' => 'Sub-Engineer',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '77',
                'name_np' => 'असिस्टेन्ट सब-ईन्जिनियर ',
                'name_en' => ' Assistant Sub-Engineer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '76',
                'name_np' => 'विद्यालय कर्मचारी ',
                'name_en' => 'School staff',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '70',
                'name_np' => 'स्वयंसेवक शिक्षक ',
                'name_en' => 'Volunteer teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '71',
                'name_np' => 'विद्यालय सहायक कर्मचारी ',
                'name_en' => 'School Support Staff',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '72',
                'name_np' => 'शिक्षक ECD ',
                'name_en' => 'Teacher ECD',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '73',
                'name_np' => 'शिक्षक ',
                'name_en' => 'teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '81',
                'name_np' => 'निजि सचिव ',
                'name_en' => 'Private Secretary',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '82',
                'name_np' => 'हलुका सवारी चालक ',
                'name_en' => 'Light vehicle driver',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '83',
                'name_np' => 'स॰ चौँथो ',
                'name_en' => 'The fourth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '84',
                'name_np' => 'कार्यालय सहयोगी तृतीय स्तर ',
                'name_en' => ' Office Assistant Level III',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '85',
                'name_np' => 'कार्यालय सहयोगी २ ',
                'name_en' => ' Office Assistant 2',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '86',
                'name_np' => 'हेल्पर ',
                'name_en' => 'Helper',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '87',
                'name_np' => 'कार्यालय सहयोगी १ ',
                'name_en' => ' Office Assistant 1',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '88',
                'name_np' => 'असिस्टेन्ट सब-ईन्जिनियर ',
                'name_en' => 'Assistant Sub-Engineer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '89',
                'name_np' => 'अ॰हे॰बे॰ ',
                'name_en' => ' hey hey',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '90',
                'name_np' => 'अ॰न॰मि॰१ ',
                'name_en' => 'A.N.M.1',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '91',
                'name_np' => ' सामाजिक परिचालक १',
                'name_en' => 'Social moderator 1',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '92',
                'name_np' => 'प्रधानाध्यापक * ',
                'name_en' => 'principal *',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '93',
                'name_np' => 'प्रधानाध्यापक * ',
                'name_en' => 'principal *',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '99',
                'name_np' => 'कार्यालय सहयोगी ',
                'name_en' => 'office assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '98',
                'name_np' => 'शिक्षक * ',
                'name_en' => 'teacher*',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '97',
                'name_np' => 'शिक्षक ',
                'name_en' => 'teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '96',
                'name_np' => 'प्रधानाध्यापक ** ',
                'name_en' => 'principal **',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '95',
                'name_np' => 'शिक्षक* ',
                'name_en' => 'teacher*',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '94',
                'name_np' => 'सहायक चौथाे ',
                'name_en' => ' Assistant quarter',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '232003',
                'name_np' => 'लेखा अधिकृत सातौ तह',
                'name_en' => 'Accounts Officer 7th Level',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '097',
                'name_np' => 'बालविकास सहजकर्ता ',
                'name_en' => ' Child Development Facilitator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '002',
                'name_np' => 'का.सहायक ',
                'name_en' => 'Karyalaya Shayek',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '500',
                'name_np' => 'वडा सचिव ',
                'name_en' => 'ward secratery',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '003',
                'name_np' => 'अधिकृत छैठौं ',
                'name_en' => ' Official Sixth',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '001',
                'name_np' => 'प्रमुख प्रसासकिय अधिकृत',
                'name_en' => 'Chief Administrative Officer',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '009',
                'name_np' => 'कायार्लय सहयोगी प्रथम ',
                'name_en' => 'Office Assistant First',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '012',
                'name_np' => 'सि॰अ॰हे॰ब॰ छैटौँ ',
                'name_en' => 'C. A. H. B. Sixth',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '100',
                'name_np' => ' शिक्षक',
                'name_en' => 'teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '100',
                'name_np' => 'प्रधानाध्यापक ',
                'name_en' => 'principal',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '105',
                'name_np' => 'शिक्षक * ',
                'name_en' => 'teacher *',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '106',
                'name_np' => 'शिक्षक * ',
                'name_en' => 'teacher *',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '107',
                'name_np' => 'प्रधानाध्यापक * ',
                'name_en' => ' principal *',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '108',
                'name_np' => 'प्रधानाध्यापक * ',
                'name_en' => 'principal *',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '109',
                'name_np' => 'प्रधानाध्यापक ** ',
                'name_en' => ' principal **',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '110',
                'name_np' => 'परिचालिका ',
                'name_en' => 'operator',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '110',
                'name_np' => 'प्र.अ. श्री रुद्र बि.क. भारती मा. वि. छथर जोरपाटी गा.पा. वडा न. १ ',
                'name_en' => 'Pra a shree Rudra b.k. bharati ma. bi. chhathar jorpati ga.pa. wada n.1',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '111',
                'name_np' => 'डा. श्री प्रशंसा नेउपाने बुधबारे -६ झापा बुद्धशान्ति गा पा -३ झापा ',
                'name_en' => 'Da. shree prashangsa neupane  budhabare -6 jhapa buddashanti ga.pa. 3 jhapa',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '112',
                'name_np' => 'श्री अर्पणा अमात्य धनकुटा न.पा.-६ ',
                'name_en' => 'shree  Arpana amatya dhankuta na.pa -6',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '112',
                'name_np' => 'अनुदान सर',
                'name_en' => '  grant sir',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '113',
                'name_np' => ' श्री पुजा थापा मगर त्रियुगा न. पा. -५ उदयपुर',
                'name_en' => 'Shree Puja thapa magar triyuga na pa -5 udayapur',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '114',
                'name_np' => ' सहायक कम्प्युटर अपरेटर तेज बहादुर लिम्बु',
                'name_en' => 'Sahayak kamputer apretar tej bahadur limbu',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '115',
                'name_np' => 'शुन्दरमान ड‌ंगोल',
                'name_en' => 'Shandur man Dangol',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '115',
                'name_np' => 'बालविकाश शिक्षक',
                'name_en' => 'Early childhood teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '116',
                'name_np' => 'प्रारम्भिक बाल विकाश शिक्षक ',
                'name_en' => 'Early Childhood Development Teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '121',
                'name_np' => 'अमिन ',
                'name_en' => 'Amin',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '15002',
                'name_np' => 'ल्याब असिस्टेन्ट ',
                'name_en' => 'Lab Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '54',
                'name_np' => 'प्रारम्भिक शिक्षक ',
                'name_en' => 'Elementary teacher',
                'status' => true,
            ],

            [
                'client_id' => 188,
                'code' => '79',
                'name_np' => 'नायब प्राविधीक सहायक ',
                'name_en' => 'Deputy Technical Assistant',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '74',
                'name_np' => 'सहायक शिक्षक ',
                'name_en' => 'assistant teacher',
                'status' => true,
            ],
            [
                'client_id' => 188,
                'code' => '75',
                'name_np' => 'बालविकाश शिक्षक ',
                'name_en' => ' Early childhood teacher',
                'status' => true,
            ],
            [
                'client_id' => 184,
                'code' => '0.1',
                'name_np' => 'सामाजिक परिचालक ',
                'name_en' => ' social operator',
                'status' => true,
            ],
            [
                'client_id' => 184,
                'code' => '005',
                'name_np' => 'सहायक पाँचाै ',
                'name_en' => 'All five assistants',
                'status' => true,
            ],
            [
                'client_id' => 184,
                'code' => '10005',
                'name_np' => 'परीक्षण ',
                'name_en' => 'tested',
                'status' => true,
            ],

        ];
        DB::table('hr_designation')->insert($rows);
    }
}
