<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenusTableSeeder extends Seeder
{
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table('menus')->truncate();
        $rows = [

            [
                'parent_id' => 0,
                'menu_name' => 'Roles Management',
                'menu_name_np' => 'भूमिका व्यवस्थापन',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-key',
                'menu_order' => 29,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 1,
                'menu_name' => 'Roles',
                'menu_name_np' => 'भूमिकाहरू',
                'menu_link' => 'roleManagement/roles',
                'menu_controller' => 'RoleController',
                'menu_icon' => 'fa fa-user-plus',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 1,
                'menu_name' => 'Permissions',
                'menu_name_np' => 'भूमिका पहुँच',
                'menu_link' => 'roleManagement/permissions',
                'menu_controller' => 'PermissionController',
                'menu_icon' => 'fa fa-unlock',
                'menu_order' => 2,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Menu Management',
                'menu_name_np' => 'मेनु व्यवस्थापन',
                'menu_link' => 'roleManagement/menus',
                'menu_controller' => 'MenuController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 31,
                'action_module_status' => true,
                'menu_module' => 'develop',
            ],
            [
                'parent_id' => '0',
                'menu_name' => 'Users Management',
                'menu_name_np' => 'प्रयोगकर्ता व्यवस्थापन',
                'menu_link' => 'users',
                'menu_controller' => 'UserController',
                'menu_icon' => 'fa fa-users',
                'menu_order' => 26,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => '6',
                'menu_name' => 'Login Logs',
                'menu_name_np' => 'लगइन व्यवस्थापन',
                'menu_link' => 'logs/loginLogs',
                'menu_controller' => 'LoginLogsController',
                'menu_icon' => 'fa fa-user-plus',
                'menu_order' => 27,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 6,
                'menu_name' => 'Failed Login Logs',
                'menu_name_np' => 'Failed लगइन व्यवस्थापन',
                'menu_link' => 'logs/failLoginLogs',
                'menu_controller' => 'FailedLoginLogsController',
                'menu_icon' => 'fa fa-user-times',
                'menu_order' => 3,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 6,
                'menu_name' => 'Action Logs',
                'menu_name_np' => 'कार्य व्यवस्थापन',
                'menu_link' => 'logs/actionLogs',
                'menu_controller' => 'ActionLogsController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 1,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'System Setting',
                'menu_name_np' => 'प्रणाली सेटिङ',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 26,
                'action_module_status' => false,
                'menu_module' => 'admin',
            ],
            [
                'parent_id' => '10',
                'menu_name' => 'App Setting',
                'menu_name_np' => 'एप सेटिङ',
                'menu_link' => 'systemSetting/appSetting',
                'menu_controller' => 'AppSettingController',
                'menu_icon' => 'fa fa-bell',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'admin',
            ],
            [
                'parent_id' => 10,
                'menu_name' => 'Mail Setting',
                'menu_name_np' => 'इमेल सेटिङ',
                'menu_link' => 'systemSetting/mailSetting',
                'menu_controller' => 'EmailSettingController',
                'menu_icon' => 'fa fa-envelope',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'admin',
            ],
            [
                'parent_id' => 10,
                'menu_name' => 'SMS Setting',
                'menu_name_np' => 'SMS सेटिङ',
                'menu_link' => 'systemSetting/smsSetting',
                'menu_controller' => 'SmsSettingController',
                'menu_icon' => 'fa fa-envelope',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'admin',
            ],
            [
                'parent_id' => 10,
                'menu_name' => 'OTP Setting',
                'menu_name_np' => 'OTP सेटिङ',
                'menu_link' => 'systemSetting/otpSetting',
                'menu_controller' => 'OtpSettingController',
                'menu_icon' => 'fa fa-envelope',
                'menu_order' => 4,
                'action_module_status' => true,
                'menu_module' => 'admin',
            ],

            [
                'parent_id' => 10,
                'menu_name' => 'Login Setting',
                'menu_name_np' => 'लगइन सेटिङ',
                'menu_link' => 'systemSetting/loginSetting',
                'menu_controller' => 'LoginSettingController',
                'menu_icon' => 'fa fa-key',
                'menu_order' => 5,
                'action_module_status' => true,
                'menu_module' => 'develop',
            ],
          
            [
                'parent_id' => 16,
                'menu_name' => 'Meeting Category',
                'menu_name_np' => 'बैठक  वर्ग',
                'menu_link' => 'masterSettings/meetingCategories',
                'menu_controller' => 'MeetingCategoryController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Meeting Status',
                'menu_name_np' => 'बैठक  स्थिति',
                'menu_link' => 'meetingstatuses',
                'menu_controller' => 'MeetingStatusController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Meeting Management',
                'menu_name_np' => 'बैठक व्यवस्थापन',
                'menu_link' => 'meetings',
                'menu_controller' => 'MeetingController',
                'menu_icon' => 'fa fa-calendar',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Meeting Member',
                'menu_name_np' => 'बैठक  सदस्य',
                'menu_link' => 'meetingMembers',
                'menu_controller' => 'MeetingMemberController',
                'menu_icon' => 'fa fa-users',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Meeting Agenda List',
                'menu_name_np' => 'बैठक  एजेन्डा सूची',
                'menu_link' => 'meetingAgendaList',
                'menu_controller' => 'MeetingAgendaListController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Final Verdict',
                'menu_name_np' => 'बैठक निर्णय',
                'menu_link' => 'finalVerdicts',
                'menu_controller' => 'FinalVerdictController',
                'menu_icon' => 'fa fa-check',
                'menu_order' => 11,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
           

            [
                'parent_id' => 0,
                'menu_name' => 'Basic Details',
                'menu_name_np' => 'आधारभुत विवरण',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-envelope',
                'menu_order' => 23,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Office',
                'menu_name_np' => 'कार्यालय',
                'menu_link' => 'basicDetails/offices',
                'menu_controller' => 'OfficeController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'Status',
                'menu_name_np' => 'स्थिति',
                'menu_link' => 'basicDetails/status',
                'menu_controller' => 'StatusController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'Letter Sending Medium',
                'menu_name_np' => 'पत्र पठाउने माध्यम',
                'menu_link' => 'basicDetails/letterSendingMedium',
                'menu_controller' => 'LetterSendingMediumController',
                'menu_icon' => 'fa fa-envelope',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Branch/Department',
                'menu_name_np' => 'शाखा/बिभाग',
                'menu_link' => 'basicDetails/branchDepartments',
                'menu_controller' => 'BranchDepartmentMediumController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 4,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'File Type',
                'menu_name_np' => 'फाइल प्रकार',
                'menu_link' => 'basicDetails/documentTypes',
                'menu_controller' => 'DocumentTypeController',
                'menu_icon' => 'fa fa-file',
                'menu_order' => 5,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Country',
                'menu_name_np' => 'देश',
                'menu_link' => 'basicDetails/countries',
                'menu_controller' => 'CountryController',
                'menu_icon' => 'fa fa-building',
                'menu_order' => 6,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Complaint Type',
                'menu_name_np' => 'गुनासोको प्रकार',
                'menu_link' => 'basicDetails/complaintTypes',
                'menu_controller' => 'ComplaintTypeController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 7,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Complaint Severity',
                'menu_name_np' => 'गुनासो गम्भीरता',
                'menu_link' => 'basicDetails/complaintSeverity',
                'menu_controller' => 'ComplaintSeverityController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 8,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Complaints Source',
                'menu_name_np' => 'गुनासो स्रोत',
                'menu_link' => 'basicDetails/complaintSource',
                'menu_controller' => 'ComplaintSourceController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 9,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Employee Designation',
                'menu_name_np' => 'कर्मचारी पद',
                'menu_link' => 'basicDetails/hr_designation',
                'menu_controller' => 'HrDesignationController',
                'menu_icon' => 'fa fa-users',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Register Book',
                'menu_name_np' => 'दर्ता किताब ',
                'menu_link' => 'dcRegisterBook',
                'menu_controller' => 'DcRegisterBookController',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'edmis',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Dispatch Book',
                'menu_name_np' => 'चलानी किताब ',
                'menu_link' => 'dcDispatchBook',
                'menu_controller' => 'DcDispatchBookController',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'edmis',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Document',
                'menu_name_np' => 'टिप्पणी',
                'menu_link' => 'dcDocument',
                'menu_controller' => 'DcDocumentController',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'edmis',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Report',
                'menu_name_np' => 'प्रतिवेदन',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-filter',
                'menu_order' => 7,
                'action_module_status' => false,
                'menu_module' => 'edmis',
            ],

            [
                'parent_id' => 38,
                'menu_name' => 'Dispatch Book',
                'menu_name_np' => 'चलानी किताब ',
                'menu_link' => 'dispatchReport',
                'menu_controller' => 'DispatchBookController',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 1,
                'action_module_status' => false,
                'menu_module' => 'edmis',
            ],
            [
                'parent_id' => 38,
                'menu_name' => 'Register Book',
                'menu_name_np' => 'दर्ता किताब ',
                'menu_link' => 'registerReport',
                'menu_controller' => 'RegisterBookController',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 2,
                'action_module_status' => false,
                'menu_module' => 'edmis',
            ],
            [
                'parent_id' => 38,
                'menu_name' => 'Letter Status',
                'menu_name_np' => 'पत्र को अवस्था ',
                'menu_link' => 'patraReport',
                'menu_controller' => 'PatraConditionController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 3,
                'action_module_status' => false,
                'menu_module' => 'edmis',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Complaint Management',
                'menu_name_np' => 'गुनासो व्यवस्थापन',
                'menu_link' => 'complaints',
                'menu_controller' => 'ComplaintController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 14,
                'action_module_status' => true,
                'menu_module' => 'ghs',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Fiscal Year',
                'menu_name_np' => 'आर्थिक वर्ष',
                'menu_link' => 'fiscalYears',
                'menu_controller' => 'FiscalYearController',
                'menu_icon' => 'fa fa-calendar',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'App Client',
                'menu_name_np' => 'एप Client',
                'menu_link' => 'appClients',
                'menu_controller' => 'AppClientController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 4,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Suggestion Category',
                'menu_name_np' => 'सुझाव प्रकार',
                'menu_link' => 'basicDetails/suggestionCategories',
                'menu_controller' => 'SuggestionTypeController',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Suggestion Details',
                'menu_name_np' => 'सुझाव विवरण',
                'menu_link' => 'suggestions',
                'menu_controller' => 'SuggestionController',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 15,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'Faq',
                'menu_name_np' => 'बारम्बार सोधिने प्रश्न',
                'menu_link' => 'basicDetails/faqs',
                'menu_controller' => 'FaqController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 16,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'Privacy & Policy',
                'menu_name_np' => 'गोपनियता नीति ',
                'menu_link' => 'basicDetails/privacyPolicies',
                'menu_controller' => 'PrivacyPolicyController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 17,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 16,
                'menu_name' => 'Setting',
                'menu_name_np' => 'सेटिङ',
                'menu_link' => 'masterSettings/settings',
                'menu_controller' => 'SettingController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 14,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Client Setting',
                'menu_name_np' => 'Client सेटिङ',
                'menu_link' => 'masterSettings/clientSettings',
                'menu_controller' => 'ClientSettingController',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 15,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Final Verdict File',
                'menu_name_np' => 'बैठक निर्णय फाइल',
                'menu_link' => 'finalVerdictFile',
                'menu_controller' => 'FinalVerdictFileController',
                'menu_icon' => 'fa fa-file',
                'menu_order' => 12,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Meeting Link List',
                'menu_name_np' => 'बैठक लिङ्क सूची',
                'menu_link' => 'meetingLinkList',
                'menu_controller' => 'MeetingLinkListController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 11,
                'action_module_status' => true,
                'menu_module' => 'mms',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Service Type',
                'menu_name_np' => 'सेवा प्रकार',
                'menu_link' => 'serviceType',
                'menu_controller' => 'ServiceTypeController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 16,
                'action_module_status' => true,
                'menu_module' => 'dcc',
            ],

            [
                'parent_id' => 16,
                'menu_name' => ' Service Department ',
                'menu_name_np' => 'सेवा विभाग',
                'menu_link' => 'serviceDepartment',
                'menu_controller' => 'ServiceDepartmentController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 16,
                'action_module_status' => true,
                'menu_module' => 'dcc',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Services',
                'menu_name_np' => 'सेवा',
                'menu_link' => 'services',
                'menu_controller' => 'ServicesController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 18,
                'action_module_status' => true,
                'menu_module' => 'dcc',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Service Related Document',
                'menu_name_np' => 'सेवा सम्बन्धित कागजात',
                'menu_link' => 'servicesRelatedDocument',
                'menu_controller' => 'ServiceRelatedDocumentController',
                'menu_icon' => 'fa fa-tasks',
                'menu_order' => 19,
                'action_module_status' => true,
                'menu_module' => 'dcc',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Api Setting',
                'menu_name_np' => 'API सेटिङ',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-book',
                'menu_order' => 25,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 57,
                'menu_name' => 'Api Key Setting',
                'menu_name_np' => 'API Key सेटिङ',
                'menu_link' => 'apiKey',
                'menu_controller' => 'ApiKeySettingController',
                'menu_icon' => 'fa fa-lock',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 57,
                'menu_name' => 'Api Access Logs',
                'menu_name_np' => 'API  लग व्यवस्थापन',
                'menu_link' => 'apiAccessLogs',
                'menu_controller' => 'ApiAccessLogController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 2,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Incident Reportings',
                'menu_name_np' => 'स्थलगत सूचना',
                'menu_link' => 'incidentReporting',
                'menu_controller' => 'IncidentReportingController',
                'menu_icon' => 'fa fa-bullhorn',
                'menu_order' => 16,
                'action_module_status' => true,
                'menu_module' => 'ghs',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Mst Settings',
                'menu_name_np' => 'Mst सेटिङहरू',
                'menu_link' => 'basicDetails/mstSetting',
                'menu_controller' => 'MstSettingController',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 7,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Karyapalika Members',
                'menu_name_np' => 'कार्यपालिका सदस्यहरु',
                'menu_link' => 'masterSettings/karyapalikaMembers',
                'menu_controller' => 'KaryapalikaMemberController',
                'menu_icon' => 'fa fa-users',
                'menu_order' => 7,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Notification List',
                'menu_name_np' => 'सूचना सूची',
                'menu_link' => 'notifications',
                'menu_controller' => 'NotificationController',
                'menu_icon' => 'fa fa-bell',
                'menu_order' => 17,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Service Token List',
                'menu_name_np' => 'सेवा टोकन सूची',
                'menu_link' => 'serviceTokenList',
                'menu_controller' => 'ServiceTokenManagementController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 20,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Service Token Log History',
                'menu_name_np' => 'सेवा टोकन लग विवरण',
                'menu_link' => 'serviceTokeLogDetails',
                'menu_controller' => 'ServiceTokenLogManagementController',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 21,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Voice Call Management',
                'menu_name_np' => 'भ्वाइस कल व्यवस्थापन',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 22,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 66,
                'menu_name' => 'Voice Record  Management',
                'menu_name_np' => 'भ्वाइस रेकर्ड व्यवस्थापन',
                'menu_link' => 'voiceRecordManagement',
                'menu_controller' => 'VoiceRecordController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 1,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Search',
                'menu_name_np' => 'खोज्नुहोस्',
                'menu_link' => 'masterSearch',
                'menu_controller' => 'MasterSearchController',
                'menu_icon' => 'fa fa-search',
                'menu_order' => 5,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Employee',
                'menu_name_np' => 'कर्मचारी',
                'menu_link' => 'employees',
                'menu_controller' => 'EmployeeController',
                'menu_icon' => 'fa fa-user',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Letter Status Log Details',
                'menu_name_np' => 'पत्र स्थिति लग विवरण',
                'menu_link' => '',
                'menu_controller' => '',
                'menu_icon' => 'fa fa-cogs',
                'menu_order' => 6,
                'action_module_status' => false,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 70,
                'menu_name' => 'Dispatch Book',
                'menu_name_np' => 'चलानी किताब',
                'menu_link' => 'dcDispacthBookStatusLogDetails',
                'menu_controller' => 'DcDispatchBookStatusLogController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 1,
                'action_module_status' => false,
                'menu_module' => 'dcc',
            ],
            [
                'parent_id' => 70,
                'menu_name' => 'Register Book',
                'menu_name_np' => 'दर्ता किताब',
                'menu_link' => 'dcRegisterBookStatusLogDetails',
                'menu_controller' => 'DcRegisterBookStatusLogController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 2,
                'action_module_status' => false,
                'menu_module' => 'dcc',
            ],

            
            [
                'parent_id' => 24,
                'menu_name' => 'Members Type',
                'menu_name_np' => 'सदस्य प्रकार',
                'menu_link' => 'membertypes',
                'menu_controller' => 'MemberTypeController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 11,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Standing List Type',
                'menu_name_np' => 'सूची प्रकार',
                'menu_link' => 'standinglisttypes',
                'menu_controller' => 'StandingListTypeController',
                'menu_order' => 12,
                'menu_icon' => 'fa fa-envelope',
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 66,
                'menu_name' => 'Phone/SMS Management',
                'menu_name_np' => 'Phone/SMS  कल  व्यवस्थापन',
                'menu_link' => 'phoneSmsManagement',
                'menu_controller' => 'PhoneSmsManagementController',
                'menu_icon' => 'fa fa-phone',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Standing List ',
                'menu_name_np' => 'सुचिकृत विवरण',
                'menu_link' => 'standinglist',
                'menu_controller' => 'StandingListController',
                'menu_order' => 12,
                'menu_icon' => 'fa fa-envelope',
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 24,
                'menu_name' => 'Organization Types',
                'menu_name_np' => 'संस्थासंग सम्बन्धित प्रकार',
                'menu_link' => 'basicDetails/organizationTypes',
                'menu_controller' => 'OrganizationTypesController',
                'menu_icon' => 'fa fa-info',
                'menu_order' => 12,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Consumer Committee',
                'menu_name_np' => 'उपभोक्ता समिति',
                'menu_link' => 'consumerCommittee',
                'menu_controller' => 'ConsumerCommitteeController',
                'menu_icon' => 'fa fa-users',
                'menu_order' => 28,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Appointment',
                'menu_name_np' => 'भेट घाट व्यवस्थापन',
                'menu_link' => 'appointments',
                'menu_controller' => 'AppointmentController',
                'menu_icon' => 'fa fa-phone',
                'menu_order' => 8,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Province',
                'menu_name_np' => 'प्रदेश',
                'menu_link' => '/provinces',
                'menu_controller' => 'ProvinceController',
                'menu_icon' => 'fa fa-building',
                'menu_order' => 2,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'District',
                'menu_name_np' => 'जिल्ला',
                'menu_link' => 'districts',
                'menu_controller' => 'DistrictController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 3,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

            [
                'parent_id' => 16,
                'menu_name' => 'Local Body Type',
                'menu_name_np' => 'स्थानीय तहको प्रकार',
                'menu_link' => 'localBodyTypes',
                'menu_controller' => 'LocalBodyTypeController',
                'menu_icon' => 'fa fa-building',
                'menu_order' => 4,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 16,
                'menu_name' => 'Local body',
                'menu_name_np' => 'स्थानिय तह',
                'menu_link' => 'localBodies',
                'menu_controller' => 'LocalBodyController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 5,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Bank',
                'menu_name_np' => 'बैंक',
                'menu_link' => 'basicDetails/bank',
                'menu_controller' => 'BankController',
                'menu_icon' => 'fas fa-university',
                'menu_order' => 11,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Visiting Purpose',
                'menu_name_np' => 'भेटघाट उद्देश्य',
                'menu_link' => 'basicDetails/vistingPurposes',
                'menu_controller' => 'VisitingPurposeController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 14,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Official Details',
                'menu_name_np' => 'जन प्रतिनिधि विवरण',
                'menu_link' => 'basicDetails/officialdetails',
                'menu_controller' => 'OfficialDetailController',
                'menu_icon' => 'fa fa-home',
                'menu_order' => 18,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Daily Working Schedule',
                'menu_name_np' => 'दैनिक कार्य तालिका',
                'menu_link' => 'dailySchedules',
                'menu_controller' => 'DailyWorkingScheduleController',
                'menu_icon' => 'fa fa-calendar',
                'menu_order' => 9,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Schedule Type',
                'menu_name_np' => 'तालिका प्रकार',
                'menu_link' => 'scheduleType',
                'menu_controller' => 'ScheduleTypeController',
                'menu_order' => 20,
                'menu_icon' => 'fa fa-envelope',
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 0,
                'menu_name' => 'Appointment Status',
                'menu_name_np' => 'भेटघाट स्थिति',
                'menu_link' => 'basicDetails/appointmentStatus',
                'menu_controller' => 'AppointmentStatusController',
                'menu_icon' => 'fa fa-calendar',
                'menu_order' => 19,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
//            [
//                'parent_id' => 0,
//                'menu_name' => 'Chat',
//                'menu_name_np' => 'च्याट',
//                'menu_link' => 'group',
//                'menu_controller' => 'GroupController',
//                'menu_icon' => 'fa fa-comment',
//                'menu_order' => 9,
//                'action_module_status' => true,
//                'menu_module' => 'chat',
//            ],

            [
                'parent_id' => 0,
                'menu_name' => 'Emergency Contact Details',
                'menu_name_np' => 'आकस्मिक सम्पर्क विवरण',
                'menu_link' => 'callRoutingNumberManagement',
                'menu_controller' => 'CallRoutingNumberManagementController',
                'menu_icon' => 'fa fa-phone',
                'menu_order' => 10,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Complaint Related Department',
                'menu_name_np' => 'गुनासो सम्बन्धित शाखा',
                'menu_link' => 'basicDetails/complaintRelatedDepartment',
                'menu_controller' => 'CallRoutingNumberManagementController',
                'menu_icon' => 'fa fa-building',
                'menu_order' => 16,
                'action_module_status' => true,
                'menu_module' => 'ghs',
            ],
            [
                'parent_id' => 24,
                'menu_name' => 'Official Videos',
                'menu_name_np' => 'आधिकारिक भिडियो',
                'menu_link' => 'basicDetails/officialVideos',
                'menu_controller' => 'OfficialVideoController',
                'menu_icon' => 'fa fa-list',
                'menu_order' => 21,
                'action_module_status' => true,
                'menu_module' => 'all',
            ],

        ];
        DB::table('menus')->insert($rows);
    }
}
