<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserRolesTableSeeder extends Seeder
{
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_roles')->truncate();
        $rows = [
            [
                'role_id' => 2,
                'menu_id' => 1,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,

            ],
            [
                'role_id' => 2,
                'menu_id' => 2,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,

            ],
            [
                'role_id' => 2,
                'menu_id' => 3,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 5,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => true,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 6,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 7,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 8,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 9,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 10,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 11,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 12,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 2,
                'menu_id' => 13,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 14,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 15,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 16,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 17,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 18,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 2,
                'menu_id' => 19,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 20,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 21,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 22,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 23,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
           
            [
                'role_id' => 2,
                'menu_id' => 25,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 26,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            
           
            [
                'role_id' => 2,
                'menu_id' => 29,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 30,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 31,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 32,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 33,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 34,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 35,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 36,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 37,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 38,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 39,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 40,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 41,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 42,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 43,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 44,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 45,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 46,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 47,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 2,
                'menu_id' => 48,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 3,
                'menu_id' => 1,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,

            ],
            [
                'role_id' => 3,
                'menu_id' => 2,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,

            ],
            [
                'role_id' => 3,
                'menu_id' => 3,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 5,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => true,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 6,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 7,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 8,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 9,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 10,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 11,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 12,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 3,
                'menu_id' => 13,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 14,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 15,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 16,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 17,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 18,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 3,
                'menu_id' => 19,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 20,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 21,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 22,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 23,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            
            [
                'role_id' => 3,
                'menu_id' => 25,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 26,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            
           
            [
                'role_id' => 3,
                'menu_id' => 29,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 30,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 31,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 32,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 33,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 34,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 35,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 36,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 37,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 38,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 39,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 40,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 41,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 42,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 43,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 44,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 45,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 46,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 47,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 3,
                'menu_id' => 48,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
           
            [
                'role_id' => 4,
                'menu_id' => 25,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 26,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 27,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 28,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 29,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 30,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 4,
                'menu_id' => 34,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 35,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 36,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 37,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 38,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 39,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 40,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 41,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 47,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 48,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 68,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 69,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 70,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 71,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 4,
                'menu_id' => 72,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 24,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 31,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 32,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 33,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 5,
                'menu_id' => 42,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 5,
                'menu_id' => 45,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 5,
                'menu_id' => 46,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 60,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 5,
                'menu_id' => 63,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 7,
                'menu_id' => 16,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 17,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 18,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 19,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 20,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 21,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 22,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 51,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 52,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],

            [
                'role_id' => 6,
                'menu_id' => 53,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 6,
                'menu_id' => 54,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 6,
                'menu_id' => 55,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 6,
                'menu_id' => 56,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 6,
                'menu_id' => 64,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 6,
                'menu_id' => 65,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 62,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 66,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 7,
                'menu_id' => 67,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 8,
                'menu_id' => 80,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
            [
                'role_id' => 8,
                'menu_id' => 88,
                'allow_index' => true,
                'allow_add' => true,
                'allow_edit' => true,
                'allow_delete' => false,
                'allow_show' => true,
            ],
          

        ];

        DB::table('user_roles')->insert($rows);
    }
}
